### ISSUE TITLE
API: Align the Tcl API with that of JavaScript, Python, R

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-tcl#11]
The JavaScript, Python, and R APIs all have functions like `seguid()`, `lsseguid()`, `csseguid()`, `ldseguid()`, and `cdseguid()`.  We should update the Tcl script to provide the same functions.

**Comment by mwdavis2** [comment]
ok, I've uploaded a new seguid.tcl file. Who knows if I messed up your build structure. It should work from source and CLI now as documented.

**Comment by HenrikBengtsson** [comment]
Excellent!  seguid-tcl now passes the API checks as well.
